import { useEffect, useMemo, useState } from 'react';
import client from '../../api/client.js';
import DocumentChecklist from '../../components/DocumentChecklist.jsx';
import MetricCard from '../../components/MetricCard.jsx';

const loanTypes = [
  { value: 'home-loan', label: 'Home Loan' },
  { value: 'personal-loan', label: 'Personal Loan' },
  { value: 'vehicle-loan', label: 'Vehicle Loan' },
  { value: 'business-loan', label: 'Business Loan' },
  { value: 'education-loan', label: 'Education Loan' },
  { value: 'gold-loan', label: 'Gold Loan' },
  { value: 'mortgage-loan', label: 'Mortgage / Loan Against Property' },
  { value: 'agricultural-loan', label: 'Agricultural Loan' }
];

const employmentTypes = [
  { value: 'salaried', label: 'Salaried' },
  { value: 'self-employed', label: 'Self-employed' }
];

const formatCurrency = (value) => new Intl.NumberFormat('en-IN', { maximumFractionDigits: 0 }).format(Number(value) || 0);

export default function ApplicantDashboard() {
  const [form, setForm] = useState({
    loanType: 'home-loan',
    employmentType: 'salaried',
    requestedAmount: 2500000,
    monthlyIncome: 100000,
    monthlyObligations: 20000,
    creditScore: 710,
    tenureMonths: 240,
    interestRate: 9.2,
    propertyValue: 0,
    identityAadhaarName: 'Ananya Sharma',
    identityPanName: 'Ananya Sharma',
    identityDob: '1992-08-17'
  });
  const [checklist, setChecklist] = useState([]);
  const [documents, setDocuments] = useState({});
  const [applications, setApplications] = useState([]);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');

  const documentGroups = useMemo(() => checklist, [checklist]);

  useEffect(() => {
    client.get('/applications/my').then((response) => setApplications(response.data.applications || []));
  }, []);

  useEffect(() => {
    client
      .post('/applications/generate-documents', {
        loanType: form.loanType,
        employmentType: form.employmentType
      })
      .then((response) => setChecklist(response.data.documentGroups || []))
      .catch(() => setChecklist([]));
  }, [form.loanType, form.employmentType]);

  const updateForm = (event) => {
    const { name, value } = event.target;
    setForm((current) => ({ ...current, [name]: value }));
  };

  const updateFile = (event) => {
    const { name, files } = event.target;
    setDocuments((current) => ({ ...current, [name]: files[0] }));
  };

  const submit = async (event) => {
    event.preventDefault();
    setError('');
    setMessage('');

    const data = new FormData();
    Object.entries(form).forEach(([key, value]) => data.append(key, value));
    data.append('identityDetails', JSON.stringify({
      aadhaarName: form.identityAadhaarName,
      panName: form.identityPanName,
      dateOfBirth: form.identityDob
    }));
    Object.entries(documents).forEach(([key, file]) => {
      if (file) {
        data.append(key, file);
      }
    });

    try {
      await client.post('/applications', data, { headers: { 'Content-Type': 'multipart/form-data' } });
      const response = await client.get('/applications/my');
      setApplications(response.data.applications || []);
      setMessage('Application submitted successfully.');
      setDocuments({});
    } catch (exception) {
      setError(exception.response?.data?.message || exception.message);
    }
  };

  const missingRequired = documentGroups.flatMap((group) => group.documents).filter((document) => document.required).length;

  return (
    <div className="space-y-8">
      <div className="grid gap-4 md:grid-cols-3">
        <MetricCard label="Loan Type" value={loanTypes.find((item) => item.value === form.loanType)?.label || form.loanType} tone="gold" />
        <MetricCard label="Employment" value={employmentTypes.find((item) => item.value === form.employmentType)?.label || form.employmentType} tone="mint" />
        <MetricCard label="Required Documents" value={missingRequired} hint="Tailored checklist is generated by loan type and employment type." />
      </div>

      <section className="rounded-[2rem] border border-white/10 bg-panel/80 p-6 shadow-glow">
        <h2 className="text-xl font-semibold text-white">Application Intake</h2>
        <p className="mt-2 text-sm text-slate-300">Change loan type or employment type and the document checklist updates immediately.</p>

        <form onSubmit={submit} className="mt-6 grid gap-4 md:grid-cols-2">
          <select name="loanType" value={form.loanType} onChange={updateForm} className="rounded-2xl border border-white/10 bg-ink px-4 py-3 text-white outline-none">
            {loanTypes.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}
          </select>
          <select name="employmentType" value={form.employmentType} onChange={updateForm} className="rounded-2xl border border-white/10 bg-ink px-4 py-3 text-white outline-none">
            {employmentTypes.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}
          </select>
          <input name="requestedAmount" value={form.requestedAmount} onChange={updateForm} placeholder="Requested amount" className="rounded-2xl border border-white/10 bg-ink px-4 py-3 text-white outline-none" />
          <input name="monthlyIncome" value={form.monthlyIncome} onChange={updateForm} placeholder="Monthly income" className="rounded-2xl border border-white/10 bg-ink px-4 py-3 text-white outline-none" />
          <input name="monthlyObligations" value={form.monthlyObligations} onChange={updateForm} placeholder="Monthly obligations" className="rounded-2xl border border-white/10 bg-ink px-4 py-3 text-white outline-none" />
          <input name="creditScore" value={form.creditScore} onChange={updateForm} placeholder="Credit score" className="rounded-2xl border border-white/10 bg-ink px-4 py-3 text-white outline-none" />
          <input name="tenureMonths" value={form.tenureMonths} onChange={updateForm} placeholder="Tenure months" className="rounded-2xl border border-white/10 bg-ink px-4 py-3 text-white outline-none" />
          <input name="interestRate" value={form.interestRate} onChange={updateForm} placeholder="Interest rate" className="rounded-2xl border border-white/10 bg-ink px-4 py-3 text-white outline-none" />
          <input name="propertyValue" value={form.propertyValue} onChange={updateForm} placeholder="Property value / collateral value" className="rounded-2xl border border-white/10 bg-ink px-4 py-3 text-white outline-none md:col-span-2" />
          <input name="identityAadhaarName" value={form.identityAadhaarName} onChange={updateForm} placeholder="Aadhaar name" className="rounded-2xl border border-white/10 bg-ink px-4 py-3 text-white outline-none" />
          <input name="identityPanName" value={form.identityPanName} onChange={updateForm} placeholder="PAN name" className="rounded-2xl border border-white/10 bg-ink px-4 py-3 text-white outline-none" />
          <input name="identityDob" value={form.identityDob} onChange={updateForm} placeholder="DOB" className="rounded-2xl border border-white/10 bg-ink px-4 py-3 text-white outline-none md:col-span-2" />

          <div className="md:col-span-2 rounded-3xl border border-white/10 bg-white/5 p-4">
            <div className="text-sm font-semibold text-white">Document upload inputs</div>
            <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
              {documentGroups.flatMap((group) => group.documents).map((document) => (
                <label key={document.id} className="rounded-2xl border border-white/10 bg-ink/60 p-3 text-sm text-slate-300">
                  <span className="block font-semibold text-white">{document.label}</span>
                  <span className="mt-1 block text-xs text-slate-400">{document.filenameHint}</span>
                  <input type="file" name={document.id} onChange={updateFile} accept=".pdf,.jpg,.jpeg,.png" className="mt-3 block w-full text-xs file:mr-3 file:rounded-full file:border-0 file:bg-gold file:px-3 file:py-2 file:font-semibold file:text-ink" />
                </label>
              ))}
            </div>
          </div>

          {message ? <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-sm text-emerald-100 md:col-span-2">{message}</div> : null}
          {error ? <div className="rounded-2xl border border-rose-500/20 bg-rose-500/10 p-3 text-sm text-rose-100 md:col-span-2">{error}</div> : null}
          <button className="rounded-2xl bg-gold px-5 py-3 font-semibold text-ink md:col-span-2">Submit application</button>
        </form>
      </section>

      <DocumentChecklist documentGroups={documentGroups} />

      <section className="rounded-[2rem] border border-white/10 bg-panel/80 p-6">
        <h2 className="text-xl font-semibold text-white">My Applications</h2>
        <div className="mt-4 space-y-4">
          {applications.map((application) => (
            <div key={application.id} className="rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-slate-300">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div className="font-semibold text-white">{application.loanType}</div>
                <div>Status: {application.status}</div>
              </div>
              <div className="mt-2 grid gap-2 sm:grid-cols-3">
                <div>Amount: ₹{formatCurrency(application.requestedAmount)}</div>
                <div>Risk score: {application.riskScore ?? 0}/100</div>
                <div>DTI: {application.debtToIncome ?? 0}%</div>
              </div>
            </div>
          ))}
          {!applications.length ? <div className="text-sm text-slate-400">No applications submitted yet.</div> : null}
        </div>
      </section>
    </div>
  );
}
